{ % set name = "ocdb-client" % }
{ % set version = "0.2.10" % }

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://github.com/eocdb/{{ name }}/archive/v{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - ocdb-cli = ocdb.main:main

requirements:
  host:
    # Python
    - python =>3.6
    - pip
  run:
    # Python
    - python =>3.6
    # Required
    - click
    - pyyaml
    - pandas
test:
  # Python imports
  imports:
    - ocdb
    - ocdb.api
    - ocdb.cli

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - ocdb-cli --help

about:
  summary: "ocdb-client is a command line interface as well as a Python API for accessing as well as managing submissions and users"
  home: https://github.com/eocdb/ocdb-client
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: "The OCDB Command Line Client is a command line interface as well as a Python API to connect an ocdb-server for accessing as well as managing submissions and users e.g. of the Copernicus Ocean Colour Database. For more information see: https://ocdb.readthedocs.io"
  doc_url: https://ocdb.readthedocs.io
  dev_url: https://github.com/eocdb/ocdb-client

extra:
  recipe-maintainers:
    - dzelge
# oc-afb140dd-c435-4492-87c4-006721ce0d8b