# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

before_script:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda;
  - export PATH="$HOME/miniconda/bin:$PATH";

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - conda config --add channels conda-forge
    - conda config --set always_yes yes --set changeps1 no
    - conda update -n base conda
    - conda install conda-build anaconda-client
    # Useful for debugging any issues with conda
    - conda info -a
    - conda env create --file environment.yml
    - source activate ocdb
    - python setup.py install

build2:
    stage: build-conda-package
    script:
        - conda build -c conda-forge recipe


test1:
  stage: test
  script:
    - pytest --cov=ocdb --cov-report html
    - conda build -c conda-forge recipe

deploy1:
  stage: deploy
  script:
    - export CONDA_UPLOAD_TOKEN=
    - bash conda/conda_upload.sh

