#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: python

os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      .\Miniconda3-latest-Windows-x86_64.exe
      setx PATH="%path%;%HOME%\miniconda\Scrips"
    else
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      hash -r
    fi
  # - conda config --add channels conda-forge
  # - conda config --set channel_priority strict
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create --file environment.yml
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      activate ocdb
    else
      source activate ocdb
    fi
  - conda list
  - python setup.py install

  - pytest --cov=ocdb --cov-report html

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      conda install conda-build
      conda install anaconda-client
      bash conda/conda_upload.sh
    fi



