#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: bash

os:
  - linux
  - osx
#  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openssl;
      choco install -y miniconda3;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - hash -r
  - conda init
  - source ~/.bashrc
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no
  - conda update -n base conda
  - conda info -a

  - conda env create --file environment.yml
  - source activate ocdb
  - conda list
  - python setup.py install

  - pytest --cov=ocdb --cov-report html

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      conda install conda-build;
      conda install anaconda-client;
      bash conda/conda_upload.sh;
    fi



